# Default values for thesis-app

apiGateway:
  replicaCount: 1
  image:
    repository: systemas32/api-gateway
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 5000
    nodePort: 30080
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

userService:
  replicaCount: 1
  image:
    repository: systemas32/user-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5001
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Health check configuration
healthCheck:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
